@startuml
'https://plantuml.com/use-case-diagram

User --> (Start)
User --> (Shoot)
User --> (Move playership)
User --> (Close game)
User --> (Collide)
(Collide) --> (Die)
(Die) --> (Start)
(Die) --> (Close game)


note right of User : User as a player.
@enduml